-- Create a PostgreSQL function to execute SQL queries safely
-- This allows us to run the SQL statements generated by the LLM

CREATE OR REPLACE FUNCTION run_query(sql text)
RETURNS TABLE(
  subject_line text,
  company text,
  sub_industry text,
  open_rate float,
  projected_volume bigint,
  date_sent date,
  campaign_name text,
  description text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Execute the provided SQL and return results
  RETURN QUERY EXECUTE sql;
END;
$$;

-- Grant execute permission to the service role
GRANT EXECUTE ON FUNCTION run_query(text) TO service_role;
