-- Create marketing campaigns table
CREATE TABLE IF NOT EXISTS marketing_campaigns (
    id SERIAL PRIMARY KEY,
    campaign_id VARCHAR(255) NOT NULL UNIQUE,
    campaign_observation_date DATE NOT NULL,
    media_channel VARCHAR(100) NOT NULL,
    marketing_company VARCHAR(100) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    subindustry VARCHAR(100),
    product_type VARCHAR(100),
    brand VARCHAR(100),
    product VARCHAR(100),
    bundled_products TEXT,
    properties VARCHAR(100),
    affiliated_company VARCHAR(100),
    post_link TEXT,
    landing_page TEXT,
    campaign_observation_country VARCHAR(10),
    estimated_volume INTEGER,
    estimated_spend DECIMAL(15,2),
    email_inbox_rate VARCHAR(50),
    email_spam_rate VARCHAR(50),
    email_read_rate VARCHAR(50),
    email_delete_rate VARCHAR(50),
    email_delete_without_read_rate VARCHAR(50),
    subject_line TEXT,
    email_sender_domain VARCHAR(255),
    social_post_type VARCHAR(50),
    social_engagement VARCHAR(50),
    digital_domain_ad_seen_on VARCHAR(255),
    panelist_location VARCHAR(100),
    metro_area VARCHAR(100),
    is_general_branding BOOLEAN DEFAULT FALSE,
    text_content TEXT,
    day_part VARCHAR(50),
    ad_duration_seconds INTEGER,
    channel VARCHAR(100),
    program VARCHAR(100),
    thumbnail_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_campaigns_media_channel ON marketing_campaigns(media_channel);
CREATE INDEX IF NOT EXISTS idx_campaigns_marketing_company ON marketing_campaigns(marketing_company);
CREATE INDEX IF NOT EXISTS idx_campaigns_industry ON marketing_campaigns(industry);
CREATE INDEX IF NOT EXISTS idx_campaigns_observation_date ON marketing_campaigns(campaign_observation_date);
CREATE INDEX IF NOT EXISTS idx_campaigns_estimated_spend ON marketing_campaigns(estimated_spend);
CREATE INDEX IF NOT EXISTS idx_campaigns_estimated_volume ON marketing_campaigns(estimated_volume);

-- Insert sample data based on the CSV
INSERT INTO marketing_campaigns (
    campaign_id,
    campaign_observation_date,
    media_channel,
    marketing_company,
    industry,
    subindustry,
    product_type,
    brand,
    product,
    bundled_products,
    properties,
    affiliated_company,
    post_link,
    landing_page,
    campaign_observation_country,
    estimated_volume,
    estimated_spend,
    email_inbox_rate,
    email_spam_rate,
    email_read_rate,
    email_delete_rate,
    email_delete_without_read_rate,
    subject_line,
    email_sender_domain,
    social_post_type,
    social_engagement,
    digital_domain_ad_seen_on,
    panelist_location,
    metro_area,
    is_general_branding,
    text_content,
    day_part,
    ad_duration_seconds,
    channel,
    program,
    thumbnail_url
) VALUES 
(
    'PAT:PIG/1001351060',
    '2025-09-05',
    'paid instagram',
    'PayPal',
    'Financial Services',
    'Banking',
    'Payment Service',
    'PayPal',
    'PayPal',
    '',
    'Consumer',
    'PayPal',
    'https://www.instagram.com/paypal/p/DNB6ZKJtw1G/',
    'None',
    'us',
    12890,
    105.98586,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'Photo',
    'None',
    'None',
    'Kansas',
    'Kansas City',
    FALSE,
    'Get smart security and added peace of mind with PayPal. Safely shop at sites around the world.',
    'None',
    NULL,
    'None',
    'None',
    'https://via.placeholder.com/150x100/4F46E5/FFFFFF?text=PayPal'
),
(
    'PAT:PIG/482601001',
    '2025-09-01',
    'paid instagram',
    'Venmo',
    'Financial Services',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'None',
    'None',
    'us',
    52164,
    428.92242,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'Reel',
    'None',
    'None',
    'Michigan',
    'Detroit',
    FALSE,
    'None',
    'None',
    NULL,
    'None',
    'None',
    'https://via.placeholder.com/150x100/059669/FFFFFF?text=Venmo'
);

-- Add more sample data for testing
INSERT INTO marketing_campaigns (
    campaign_id,
    campaign_observation_date,
    media_channel,
    marketing_company,
    industry,
    estimated_volume,
    estimated_spend,
    thumbnail_url
) VALUES 
('PAT:FB/2001351060', '2025-08-28', 'paid facebook', 'Chase', 'Financial Services', 25000, 350.50, 'https://via.placeholder.com/150x100/DC2626/FFFFFF?text=Chase'),
('PAT:GOOG/3001351060', '2025-08-25', 'paid google', 'Wells Fargo', 'Financial Services', 18000, 280.75, 'https://via.placeholder.com/150x100/7C3AED/FFFFFF?text=Wells+Fargo'),
('PAT:TW/4001351060', '2025-08-22', 'paid twitter', 'Bank of America', 'Financial Services', 32000, 450.25, 'https://via.placeholder.com/150x100/1E40AF/FFFFFF?text=BofA'),
('PAT:YT/5001351060', '2025-08-20', 'paid youtube', 'Capital One', 'Financial Services', 15000, 220.80, 'https://via.placeholder.com/150x100/F59E0B/FFFFFF?text=Capital+One'),
('PAT:IG/6001351060', '2025-08-18', 'paid instagram', 'American Express', 'Financial Services', 28000, 380.90, 'https://via.placeholder.com/150x100/EF4444/FFFFFF?text=AmEx'),
('PAT:FB/7001351060', '2025-08-15', 'paid facebook', 'Discover', 'Financial Services', 12000, 195.60, 'https://via.placeholder.com/150x100/10B981/FFFFFF?text=Discover'),
('PAT:GOOG/8001351060', '2025-08-12', 'paid google', 'Citi', 'Financial Services', 22000, 320.40, 'https://via.placeholder.com/150x100/8B5CF6/FFFFFF?text=Citi'),
('PAT:TW/9001351060', '2025-08-10', 'paid twitter', 'US Bank', 'Financial Services', 16000, 240.30, 'https://via.placeholder.com/150x100/06B6D4/FFFFFF?text=US+Bank');
